[versions]
accompanist = "0.31.0-alpha"
androidx-credentials = "1.0.0-alpha09"
androidx-hilt = "1.1.0-alpha01"
autodagger = "0.6.5"
coil = "2.4.0"
com-google-android-gms = "18.1.0"
compose = "1.6.0-alpha02"
google-services = "4.3.15"
hilt = "2.47"
hilt-compiler = "1.0.0"
lumberjack = "5.3.1"
media3 = "1.1.1"
mockk = "1.13.5"
moshi = "1.15.0"
okhttp = "5.0.0-alpha.11"
org-jetbrains-kotlinx = "1.7.3"
permissions = "1.2.0"
retrofit = "2.9.0"
sqldelight = "2.0.0"

[libraries]
about = "com.mikepenz:aboutlibraries-compose:10.8.3"
accompanist-drawable = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
# @pin until 1.8.0 does not require sdkPreview support
androidx-activity = "androidx.activity:activity-compose:1.7.2"
androidx-annotation = "androidx.annotation:annotation:1.6.0"
androidx-compose-animation-base = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-compose-constraintlayout = "androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha12"
androidx-compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-windowsize = "androidx.compose.material3:material3-window-size-class:1.1.1"
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.7.0"
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-constraint = "androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha12"
androidx-core = "androidx.core:core-ktx:1.10.1"
androidx-credentials-core = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.1.0-alpha04"
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
androidx-media3-core = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-database = { module = "androidx.media3:media3-database", version.ref = "media3" }
androidx-media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
androidx-preference = "androidx.preference:preference-ktx:1.2.1"
androidx-splash = "androidx.core:core-splashscreen:1.0.1"
androidx-startup = "androidx.startup:startup-runtime:1.2.0-alpha02"
androidx-tracing = "androidx.tracing:tracing-ktx:1.1.0"
androidx-window = "androidx.window:window:1.1.0"
androidx-work = "androidx.work:work-runtime-ktx:2.8.1"
androidx-work-hilt = "androidx.hilt:hilt-work:1.0.0"
appcenter-crashes= "com.microsoft.appcenter:appcenter-crashes:5.0.2"
appyx = "com.bumble.appyx:core:1.3.0"
assure = "com.afollestad.assure:coroutines:0.2.0"
autodagger-core = { module = "se.ansman.dagger.auto:android", version.ref = "autodagger" }
autodagger-kapt = { module = "se.ansman.dagger.auto:compiler", version.ref = "autodagger" }
bubble-navigation = "com.github.savvasdalkitsis:BubbleNavigationBarCompose:1.0.2"
crop = "com.github.moyuruaizawa:cropify:0.3.1"
coil-base = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
exif = "androidx.exifinterface:exifinterface:1.3.6"
flowpreferences = "com.fredporciuncula:flow-preferences:1.9.1"
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
gif = "com.squareup:gifencoder:0.10.1"
gson = "com.google.code.gson:gson:2.10.1"
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
imaging = "org.apache.commons:commons-imaging:1.0-alpha3"
infobar = "com.radusalagean:info-bar-compose:1.0.0"
jetlime = "io.github.pushpalroy:jetlime:1.0.3"
joda-time = "net.danlew:android.joda:2.12.5"
jwt = "com.auth0.android:jwtdecode:2.0.2"
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlin-reflect = "org.jetbrains.kotlin:kotlin-reflect:1.9.0"
logger = "com.jakewharton.timber:timber:4.7.1"
lottie = "com.airbnb.android:lottie-compose:6.1.0"
lumberjack-core = { module = "com.github.savvasdalkitsis.Lumberjack:lumberjack-library", version.ref = "lumberjack" }
lumberjack-feedback = { module = "com.github.savvasdalkitsis.Lumberjack:lumberjack-feedback", version.ref = "lumberjack" }
lumberjack-feedback-manager = "com.github.MFlisar:FeedbackManager:2.0.3"
lumberjack-file = { module = "com.github.savvasdalkitsis.Lumberjack:lumberjack-filelogger", version.ref = "lumberjack" }
lumberjack-notification = { module = "com.github.savvasdalkitsis.Lumberjack:lumberjack-notification", version.ref = "lumberjack" }
mapbox = "com.mapbox.maps:android:10.9.1"
maplibre = "org.maplibre.gl:android-sdk:10.2.0"
maplibre-annotations = "org.maplibre.gl:android-plugin-annotation-v9:2.0.0"
maps = { module = "com.google.android.gms:play-services-maps", version.ref = "com-google-android-gms" }
maps-compose = "com.google.maps.android:maps-compose:2.13.0"
maps-utils = "com.google.maps.android:android-maps-utils:3.5.2"
maps-utils-ktx = "com.google.maps.android:maps-utils-ktx:3.4.0"
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-ksp = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-url = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
palette = "androidx.palette:palette-ktx:1.0.0"
permissions-base = { module = "dev.shreyaspatil.permission-flow:permission-flow-android", version.ref = "permissions" }
permissions-compose = { module = "dev.shreyaspatil.permission-flow:permission-flow-compose", version.ref = "permissions" }
play = "com.google.android.gms:play-services-base:18.2.0"
recasa = "com.github.sebaslogen.resaca:resaca:2.4.6"
reorder = "org.burnoutcrew.composereorderable:reorderable:0.9.6"
remember = "dev.burnoo:compose-remember-preference:1.0.1"
result = "com.michael-bull.kotlin-result:kotlin-result:1.1.18"
result-coroutines = "com.michael-bull.kotlin-result:kotlin-result-coroutines:1.1.18"
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
scrollbar = "com.github.nanihadesuka:LazyColumnScrollbar:1.7.2"
sqldelight-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-gradle-plugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
timeline = "com.github.yeocak:ComposableTimelineView:0.6"
urlvalidator = "commons-validator:commons-validator:1.7"
vico = "com.patrykandpatrick.vico:compose-m2:1.9.2"
videocache = "com.github.Andrew0000:Android-VideoView-cache:1.0.15"
zoomable = "com.mxalbert.zoomable:zoomable:1.6.1"

[bundles]
androidx-compose-animation = [
    "androidx-compose-animation-base",
    "androidx-compose-animation-graphics",
]
androidx-credentials = [
    "androidx-credentials-core",
    "androidx-credentials-play",
]
androidx-media3 = [
    "androidx-media3-core",
    "androidx-media3-database",
    "androidx-media3-hls",
    "androidx-media3-okhttp",
    "androidx-media3-ui",
]
lumberjack = [
    "lumberjack-core",
    "lumberjack-feedback",
    "lumberjack-feedback-manager",
    "lumberjack-file",
    "lumberjack-notification",
]
permissions = [
    "permissions-base",
    "permissions-compose",
]