[versions]
about = "11.2.3"
accompanist = "0.34.0"
agp = "8.5.2"
android-sdk-geojson = "6.0.1"
androidx-hilt = "1.2.0"
autodagger = "1.3.0"
coil = "2.7.0"
compose = "1.7.0-rc01"
crypto = "1.1.0-alpha06"
datastore = "1.1.1"
gms = "19.0.0"
google-services = "4.4.2"
hilt = "2.52"
hilt-compiler = "1.2.0"
kotlin = "2.0.20"
kotlinx = "1.8.1"
lumberjack = "6.0.7"
media3 = "1.4.1"
mockk = "1.13.12"
moshi = "1.15.1"
okhttp = "5.0.0-alpha.11"
permissions = "1.2.0"
resaca = "3.2.0"
result = "2.0.0"
retrofit = "2.11.0"
sqldelight = "2.0.2"

[plugins]
about = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about" }
android-app = { id = 'com.android.application', version.ref = "agp" }
android-library = { id = 'com.android.library', version.ref = "agp" }
analysis = "com.autonomousapps.dependency-analysis:2.0.2"
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:2.0.20-1.0.24"
moduleGraph = "com.savvasdalkitsis.module-dependency-graph:0.12"
powerassert = "org.jetbrains.kotlin.plugin.power-assert:2.0.20"
redacted = "dev.zacsweers.redacted:1.10.0"
sonarqube = "org.sonarqube:5.1.0.4882"
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
about = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "about" }
accompanist-drawable = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
android-sdk-geojson = { module = "org.maplibre.gl:android-sdk-geojson", version.ref = "android-sdk-geojson" }
androidx-activity = "androidx.activity:activity-compose:1.9.2"
androidx-annotation = "androidx.annotation:annotation:1.8.2"
androidx-compose-animation-base = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
androidx-compose-constraintlayout = "androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha14"
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-windowsize = "androidx.compose.material3:material3-window-size-class:1.2.1"
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.7.7"
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-core = "androidx.core:core-ktx:1.13.1"
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.2"
androidx-media3-core = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-database = { module = "androidx.media3:media3-database", version.ref = "media3" }
androidx-media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-preference = "androidx.preference:preference-ktx:1.2.1"
androidx-security-crypto-core = { module = "androidx.security:security-crypto", version.ref = "crypto" }
androidx-security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "crypto" }
androidx-splash = "androidx.core:core-splashscreen:1.0.1"
androidx-startup = "androidx.startup:startup-runtime:1.2.0-beta01"
androidx-tracing = "androidx.tracing:tracing-ktx:1.2.0"
androidx-window = "androidx.window:window:1.3.0"
androidx-work = "androidx.work:work-runtime-ktx:2.9.1"
androidx-work-hilt = "androidx.hilt:hilt-work:1.2.0"
appyx = "com.bumble.appyx:core:1.4.0"
assure = "com.afollestad.assure:coroutines:0.2.0"
autodagger-core = { module = "se.ansman.dagger.auto:android", version.ref = "autodagger" }
autodagger-kapt = { module = "se.ansman.dagger.auto:compiler", version.ref = "autodagger" }
autodagger-retrofit = { module = "se.ansman.dagger.auto:retrofit", version.ref = "autodagger" }
bottomsheet = "com.holix.android:bottomsheetdialog-compose:1.5.0"
bubble-navigation = "com.github.savvasdalkitsis:BubbleNavigationBarCompose:1.0.2"
bugsnag = "com.bugsnag:bugsnag-android:6.7.0"
bugsnag-plugin = "com.bugsnag:bugsnag-android-gradle-plugin:8.1.0"
capturable = "com.github.SmartToolFactory:Compose-Screenshot:1.0.3"
coil-base = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
crop = "com.github.moyuruaizawa:cropify:0.3.1"
exif = "androidx.exifinterface:exifinterface:1.3.7"
flowpreferences = "com.fredporciuncula:flow-preferences:1.9.1"
gif = "com.squareup:gifencoder:0.10.1"
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
gson = "com.google.code.gson:gson:2.11.0"
heatmap = "com.github.k-surtel:heat-map:1.0.1"
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
imaging = "org.apache.commons:commons-imaging:1.0.0-alpha5"
infobar = "com.radusalagean:info-bar-compose:1.0.0"
jetlime = "io.github.pushpalroy:jetlime:2.3.0"
joda-time = "net.danlew:android.joda:2.12.7"
junit = "junit:junit:4.13.2"
jwt = "com.auth0.android:jwtdecode:2.0.2"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx" }
kotlinx-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7"
leaks = "com.squareup.leakcanary:leakcanary-android:2.14"
lottie = "com.airbnb.android:lottie-compose:6.5.1"
lumberjack-core = { module = "com.github.MFlisar.Lumberjack:core", version.ref = "lumberjack" }
lumberjack-implementation = { module = "com.github.MFlisar.Lumberjack:implementation-lumberjack", version.ref = "lumberjack" }
lumberjack-logger-console = { module = "com.github.MFlisar.Lumberjack:logger-console", version.ref = "lumberjack" }
lumberjack-logger-file = { module = "com.github.MFlisar.Lumberjack:logger-file", version.ref = "lumberjack" }
lumberjack-extension-feedback = { module = "com.github.MFlisar.Lumberjack:extension-feedback", version.ref = "lumberjack" }
lumberjack-extension-notification = { module = "com.github.MFlisar.Lumberjack:extension-notification", version.ref = "lumberjack" }
lumberjack-extension-viewer = { module = "com.github.MFlisar.Lumberjack:extension-viewer", version.ref = "lumberjack" }
mapbox = "com.mapbox.maps:android:11.6.0"
maplibre = "org.maplibre.gl:android-sdk:11.2.0"
maplibre-annotations = "org.maplibre.gl:android-plugin-annotation-v9:3.0.0"
maps = { module = "com.google.android.gms:play-services-maps", version.ref = "gms" }
maps-compose = "com.google.maps.android:maps-compose:6.1.1"
maps-utils = "com.google.maps.android:android-maps-utils:3.8.2"
maps-utils-ktx = "com.google.maps.android:maps-utils-ktx:5.1.1"
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-ksp = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-url = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
palette = "androidx.palette:palette-ktx:1.0.0"
permissions-base = { module = "dev.shreyaspatil.permission-flow:permission-flow-android", version.ref = "permissions" }
permissions-compose = { module = "dev.shreyaspatil.permission-flow:permission-flow-compose", version.ref = "permissions" }
play = "com.google.android.gms:play-services-base:18.5.0"
remember = "dev.burnoo:compose-remember-preference:1.1.0"
reorder = "org.burnoutcrew.composereorderable:reorderable:0.9.6"
resaca-core = { module = "io.github.sebaslogen:resaca", version.ref = "resaca" }
resaca-hilt = { module = "io.github.sebaslogen:resacahilt", version.ref = "resaca" }
result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "result" }
result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "result" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
scrollbar = "com.github.nanihadesuka:LazyColumnScrollbar:1.9.0"
seeker = "io.github.2307vivek:seeker:1.2.2"
shazamcrest = "com.shazam:shazamcrest:0.11"
sqldelight-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-gradle-plugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
telephoto = "me.saket.telephoto:zoomable-image-coil:0.13.0"
timeline = "com.github.yeocak:ComposableTimelineView:0.6"
turbine = "app.cash.turbine:turbine:1.0.0"
urlvalidator = "commons-validator:commons-validator:1.9.0"
vico = "com.patrykandpatrick.vico:compose-m2:1.15.0"
videocache = "com.github.Andrew0000:Android-VideoView-cache:1.0.15"
zoomable = "com.mxalbert.zoomable:zoomable:1.6.2"

[bundles]
androidx-compose-animation = [
    "androidx-compose-animation-base",
    "androidx-compose-animation-graphics",
]
androidx-media3 = [
    "androidx-media3-core",
    "androidx-media3-database",
    "androidx-media3-hls",
    "androidx-media3-okhttp",
    "androidx-media3-ui",
]
androidx-security-crypto = [
    "androidx-security-crypto-core",
    "androidx-security-crypto-ktx",
]
autodagger = [
    "autodagger-core",
    "autodagger-retrofit",
]
lumberjack = [
    "lumberjack-core",
    "lumberjack-implementation",
    "lumberjack-logger-console",
    "lumberjack-logger-file",
    "lumberjack-extension-feedback",
    "lumberjack-extension-notification",
    "lumberjack-extension-viewer",
]
permissions = [
    "permissions-base",
    "permissions-compose",
]
resaca = [
    "resaca-core",
    "resaca-hilt",
]
result = [
    "result",
    "result-coroutines",
]
test = [
    "junit",
    "kotlinx-coroutines-test",
    "mockk",
    "shazamcrest",
    "turbine",
]
